version: "3.3"
services:
  api_service:
    image: asabedia/fieldfresh-api:1
    restart: always
    ports:
      - 9090:9090
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:8888/fieldfresh?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - db
    networks:
      - api_net
  db:
    image: kartoza/postgis:11.5-2.5
    restart: always
    environment:
      - POSTGRES_DB=fieldfresh
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    expose:
      - "8888"
    ports:
      - "8888:5432"
    networks:
      - api_net
networks:
  api_net:
