version: "3.3"
services:
  api_service:
    image: 059394117896.dkr.ecr.us-east-1.amazonaws.com/fieldfresh-api:2e84640aa47cefacf42941f63c759f0fa63cdb29
    ports:
      - 9090:9090
    environment:
      - DB_URL=jdbc:postgresql://db:5432/fieldfresh?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - db
    networks:
      - api_net
  db:
    image: kartoza/postgis:11.5-2.5
    restart: always
    environment:
      - POSTGRES_DB=fieldfresh
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    expose:
      - "8888"
    ports:
      - "8888:5432"
    networks:
      - api_net
networks:
  api_net:
