version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.9.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - master
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${AWS_ECR_REPO_NAME}
          tag: 'latest'
          extra-build-args: '--build-arg AWS_ACCESS_KEY_ID_ARG=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_ACCESS_KEY_ARG=${AWS_SECRET_ACCESS_KEY} --build-arg AWS_REGION=${AWS_REGION}'