create sequence hibernate_sequence start with 1;

create table buy_products_AUD
(
    id              char(26) not null,
    status          varchar,
    earliest_date   timestamp,
    latest_date     timestamp,
    max_price_cents bigint,
    volume          integer,
    buy_order_id    char(25),
    product_id      char(24),
    created_at      timestamp,
    updated_at      timestamp,
    can_cancel      boolean,
    REV     INTEGER NOT NULL,
    REVTYPE SMALLINT
);

create table sell_products_AUD
(
    id              char(26) not null,
    status          varchar,
    earliest_date   timestamp,
    latest_date     timestamp,
    service_radius  double precision,
    min_price_cents bigint,
    volume          integer,
    sell_order_id   char(25),
    product_id      char(24),
    created_at      timestamp,
    updated_at      timestamp,
    picture_url     varchar,
    can_cancel      boolean,
    REV     INTEGER NOT NULL,
    REVTYPE SMALLINT
);

CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT
        AS IDENTITY ( START WITH 1 ),
    revtstmp BIGINT,
    PRIMARY KEY ( rev )
);

ALTER TABLE buy_products
ALTER COLUMN volume TYPE INTEGER;

ALTER TABLE sell_products
ALTER COLUMN volume TYPE INTEGER;

ALTER TABLE matches
ALTER COLUMN quantity TYPE INTEGER;

